### ISSUE TITLE
Navigation not stopping when closing the app or navigating away

### ISSUE THREAD

**Issue by ziga-hvalec** [googlemaps/react-native-navigation-sdk#34]
Hi. I’m having issues with the navigation sdk. 
i tried multiple ways to handle this but wasn’t yet able to find anything that works reliably. 

I tried implementing this in the following way. When user navigates to a screen and start navigation which works okay. If from this screen user navigates back navigation continues even though component is completely unmounted. If they go back to this screen, on ios navigation gets stopped while on android it continues. 

I tried fixing this myself by stopping guidance when user navigates away and restarting it when te focus navigation view. But this causes the next issue. Voice instructions on ios sometimes continue for a few seconds. if user in that time goes back to navigation both new and old voice instructions are played for a few seconds but only on ios. 

I also did the same when app goes to background. I stop guidance and restart it once user opens the app again. Here i have the same issue as above. It mostly happens on ios but i had this happen on android as well.

I also noticed that if i simply closed the app on android navigation kept going even when app was completely closed. I don’t know how to stop guidance when app shuts down. This doesn’t happen every time. but it’s very common. 

#### Code example

```js
<NavigationView
  width={navViewWidth}
  height={navViewHeight}
  androidStylingOptions={{}}
  iOSStylingOptions={{}}
  navigationViewCallbacks={navigationViewCallbacks}
  mapViewCallbacks={mapViewCallbacks}
  onMapViewControllerCreated={setMapViewController}
  onNavigationViewControllerCreated={setNavigationViewController}
  termsAndConditionsDialogOptions={termsAndConditionsDialogOptions}
/> 
```

I then call to start guidance and simulation 
```js 
navigationViewController?.setDestination(waypoint, routingOptions);
navigationViewController?.startGuidance();
navigationViewController?.simulator.simulateLocationsAlongExistingRoute({speedMultiplier: 5,});
```

 I also call  to stop guidance when app goes to background or screen unfocuses
```js
navigationViewController?.stopGuidance(); 
```

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
navigation sdk
2. OS type and version
android 14 and ios 16
3. Library version and other environment information
tag 0.1.1

**Comment by akilakumarasamy** [comment]
Is this addressed in latest releases? This is making a security and privacy threat for the users when it continues to talk. User are not comfortable to use thinking we are tracking them even after the app is closed.

**Comment by jokerttu** [comment]
> Is this addressed in latest releases? This is making a security and privacy threat for the users when it continues to talk. User are not comfortable to use thinking we are tracking them even after the app is closed.

With the latest version of the library, you can stop and clean up the navigation using the `cleanup` method of the `NavigationController`. This should be done when your application goes into the background.

If this doesn't resolve the issue, please provide more details to continue the discussion.

**Comment by ziga-hvalec** [comment]
what do you mean when going to background? do you mean this should be called when app gets minimized? would that mean we should restart navigation when maximizing the app again? or should this only be called when trying to stop navigation e.g. going to next screen or navigating back? 
if we call this cleanup method, do we still need to call stop guidance and stop simulator stopLocationSimulation?

**Comment by ziga-hvalec** [comment]
Any update on this? This is still an issue on v0.6.1. App is still giving directions even after quitting the app(swipe up, dismiss app)

**Comment by jokerttu** [comment]
@ziga-hvalec currently working on solution for this.
